// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SalesReport struct {
	SReportID   uuid.UUID        `json:"s_report_id"`
	ReportType  string           `json:"report_type"`
	StartDate   pgtype.Timestamp `json:"start_date"`
	EndDate     pgtype.Timestamp `json:"end_date"`
	TotalSales  pgtype.Numeric   `json:"total_sales"`
	TotalOrders pgtype.Int4      `json:"total_orders"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type UserReport struct {
	UReportID  uuid.UUID        `json:"u_report_id"`
	UserID     uuid.UUID        `json:"user_id"`
	ReportType string           `json:"report_type"`
	TotalValue pgtype.Numeric   `json:"total_value"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
