// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSalesReports(ctx context.Context, arg CreateSalesReportsParams) (SalesReport, error)
	CreateUserReport(ctx context.Context, arg CreateUserReportParams) (UserReport, error)
	GetSalesReportsByDate(ctx context.Context, startDate pgtype.Timestamp) ([]SalesReport, error)
	GetSalesReportsById(ctx context.Context, sReportID uuid.UUID) (SalesReport, error)
	GetSalesReportsList(ctx context.Context) ([]SalesReport, error)
	GetUserReportById(ctx context.Context, uReportID uuid.UUID) (UserReport, error)
	GetUserReportByOverTotalValue(ctx context.Context, totalValue pgtype.Numeric) ([]UserReport, error)
	GetUserReportByUserId(ctx context.Context, userID uuid.UUID) ([]UserReport, error)
}

var _ Querier = (*Queries)(nil)
